### ISSUE TITLE
Collect method inputs for each return value

### ISSUE THREAD

**Issue by khaes-kth** [algomaster99/collector-sahab#19]
We also want to collect method inputs that have lead to each return value.

**Comment by algomaster99** [comment]
I had a go at this issue. Turns out [`Method.arguments()`](https://docs.oracle.com/javase/7/docs/jdk/api/jpda/jdi/com/sun/jdi/Method.html#arguments()) is not sufficient. If the argument is modified in the body of the method, the modified argument shall be returned. However, we desire the original argument.
